In [1]:
# Import necessary libraries
from pycaret.classification import *

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data=pd.read_csv('Data.csv')

In [4]:
data.head()

,class,cap-diameter,cap-shape,cap-surface,cap-color,does-bruise-or-bleed,gill-attachment,gill-spacing,gill-color,stem-height,...,stem-root,stem-surface,stem-color,veil-type,veil-color,has-ring,ring-type,spore-print-color,habitat,season
0,p,15.26,x,g,o,f,e,NaN,w,16.95,...,s,y,w,u,w,t,g,NaN,d,w
1,p,16.60,x,g,o,f,e,NaN,w,17.99,...,s,y,w,u,w,t,g,NaN,d,u
2,p,14.07,x,g,o,f,e,NaN,w,17.80,...,s,y,w,u,w,t,g,NaN,d,w
3,p,14.17,f,h,e,f,e,NaN,w,15.77,...,s,y,w,u,w,t,p,NaN,d,w
4,p,14.64,x,h,o,f,e,NaN,w,16.53,...,s,y,w,u,w,t,p,NaN,d,w

In [5]:
# Setup PyCaret for classification
clf = setup(data=data, target='class', session_id=123)

# Compare different models and choose the best one
best_model = compare_models()

In [6]:


# Create a specific model (e.g., Random Forest)
rf_model = create_model('rf')

# Tune the Random Forest model
tuned_rf = tune_model(rf_model)

# Evaluate the tuned model
evaluate_model(tuned_rf)

# Make predictions on new data (if available)
# predictions = predict_model(tuned_rf, data=new_data)

# Finalize the model (train on the full dataset)
#final_rf_model = finalize_model(tuned_rf)

# Save the model
#save_model(final_rf_model, 'final_rf_model')

# Load the model later
#loaded_rf_model = load_model('final_rf_model')

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelinâ€¦